name:                my-project
version:             0.1.0.0
github:              "Maickel-Hartlief/BP"
license:             BSD3
author:              "Maickel Hartlief"
maintainer:          "m.hartlief@sudent.rug.nl"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/my-project#readme>

dependencies:
- base >= 4.7 && < 5
- smcdel

library:
  source-dirs: src
  ghc-options:
    - -Wall
  ghci-options:
    - -Wall

executables:
  my-project-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - my-project
    - random
    - criterion

tests:
  my-project-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - my-project
    - hspec
    - QuickCheck
  my-project-graph:
    main:               criterion2pgfplotcsv.unix.hs
    source-dirs:        graph
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - my-project
    - Text
    - Data


benchmarks:
  bench-muddychildren:
     source-dirs:     app
     main:            Main.hs
     dependencies:
       - my-project
       - criterion